import argparse
import subprocess
import sys
import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
WORKSPACE_DIR = ROOT_DIR.parent
DA_CLIP_CFG = WORKSPACE_DIR / "baselines" / "DA-CLIP" / "universal-image-restoration" / "config" / "daclip-sde"
THIRD_PARTY_EMA = ROOT_DIR / "third_party_ema"


def parse_args():
    parser = argparse.ArgumentParser(description="Launch official DA-CLIP training with generated P2 options.")
    parser.add_argument(
        "--opt",
        default=str(ROOT_DIR / "experiments" / "daclip_p2_train.yml"),
        help="Option file generated by prepare_p2_daclip_baseline.py.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    opt_path = Path(args.opt)
    train_py = DA_CLIP_CFG / "train.py"

    if not train_py.exists():
        raise FileNotFoundError(train_py)
    if not opt_path.exists():
        raise FileNotFoundError(
            f"{opt_path}\nRun prepare_p2_daclip_baseline.py before this launcher."
        )

    print("[Protocol] P2 all-in-one DA-CLIP baseline.")
    print("[Protocol] Official DA-CLIP universal-image-restoration training code.")
    print("[Protocol] Uses generated option file:")
    print(f"  {opt_path}")
    print("[Launch]")
    print(f'  cwd={DA_CLIP_CFG}')
    print(f'  {sys.executable} train.py -opt "{opt_path}"')

    env = os.environ.copy()
    if THIRD_PARTY_EMA.exists():
        env["PYTHONPATH"] = str(THIRD_PARTY_EMA) + os.pathsep + env.get("PYTHONPATH", "")

    subprocess.run(
        [sys.executable, "train.py", "-opt", str(opt_path)],
        cwd=str(DA_CLIP_CFG),
        env=env,
        check=True,
    )


if __name__ == "__main__":
    main()
